### ISSUE TITLE
Make reducer's reducerKey and slice match given subsection name

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-subsection-generator#19]
With the change to the `singularize`d name, the reducer slice no longer matches the folder hierarchy. For example,
```sh
yarn generate-subsection todos
```
Results in
```js
const reducerKey = 'todo'
// const slice = 'root.todo'
```
Was this intended? It seems a little counter intuitive to me. Conversely, maybe the folder should be singularized?

**Comment by dpikt** [comment]
Hmm, interesting. I don't think that was intentional. Ideally it would match the initial name that was given to the command (and consequently match the folder hierarchy).

**Comment by mwislek** [comment]
Resolved by PR: https://github.com/LaunchPadLab/lp-subsection-generator/pull/29
